[package]
name = "shs_core"
version = "0.1.0"
authors = ["sean billig <sean.billig@gmail.com>"]
edition = "2018"

[dependencies]
sodiumoxide = "0.2.0"
libsodium-sys = "0.2.0"

[dev-dependencies]
criterion = "~0.2.10"

[[bench]]
name = "bench"
harness = false
