[package]
name = "shs_core"
version = "0.1.0"
authors = ["sean billig <sean.billig@gmail.com>"]
edition = "2018"
license = "AGPL-3.0"
description = "Secret-handshake protocol core"
repository = "https://github.com/sbillig/shs_core"
documentation = "https://docs.rs/shs_core/"
readme = "README.md"
keywords = ["secret handshake", "handshake", "ssb", "scuttlebutt", "crypto"]

[dependencies]
sodiumoxide = "0.2.0"
libsodium-sys = "0.2.0"

[dev-dependencies]
criterion = "~0.2.10"
hex = "0.3"

[[bench]]
name = "bench"
harness = false
