[package]
name = "shs_core"
version = "0.2.3"
authors = ["sean billig <sean.billig@gmail.com>"]
edition = "2018"
license = "AGPL-3.0"
description = "Secret-handshake protocol core"
repository = "https://github.com/sbillig/shs_core"
documentation = "https://docs.rs/shs_core/"
readme = "README.md"
keywords = ["secret-handshake", "handshake", "ssb", "scuttlebutt", "crypto"]

[dependencies]
quick-error = "1.2"
ssb-crypto = "0.1"

[dev-dependencies]
criterion = "~0.2.10"

[[bench]]
name = "bench"
harness = false
