[package]
name = "shs"
version = "0.3.0"
authors = ["sean billig <sean.billig@gmail.com>"]
edition = "2018"
license = "AGPL-3.0"
description = "Secret-handshake protocol core"
repository = "https://github.com/sunrise-choir/shs_core"
documentation = "https://docs.rs/shs_core/"
readme = "README.md"
keywords = ["secret-handshake", "handshake", "ssb", "scuttlebutt", "crypto"]

[dependencies]
futures-preview = "0.3.0-alpha.16"
quick-error = "1.2"
ssb-crypto = "~0.1.2"

[dev-dependencies]
async-ringbuffer = "0.5.1"
criterion = "~0.2.10"
hex = "0.3.2"
futures-util-preview = "0.3.0-alpha.16"
pin-utils = "0.1.0-alpha.4"
readwrite = "0.1.1"

[[bench]]
name = "bench"
harness = false
